name: security

services:
  security:
    environment:
      - LOG_LEVEL=error
      - APP_DEBUG=false
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: always

  gateway:
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: always
